version: "3.9"
services:
  weather_api:
    build: .
    ports:
      - '8090:8090'
    container_name: weather_api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://weather_db:5432/bookdb
      - SPRING_DATASOURCE_USERNAME=book-user
      - SPRING_DATASOURCE_PASSWORD=k9ZqLC
    links:
      - 'weather_db:database'

  weather_db:
    image: postgres:13.2-alpine
    container_name: 'weather_db'
    environment:
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/data/postgres
    ports:
      - "5555:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: